// Generated by CoffeeScript 1.3.3
(function() {
  var applyRule, myArr;

  applyRule = function(arr) {
    var i, x, y, z, _i, _ref;
    for (i = _i = 0, _ref = arr.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      if (i - 1 < 0) {
        x = arr[arr.length - 1];
      } else {
        x = arr[i - 1];
      }
      y = arr[i];
      if (i + 1 === arr.length) {
        z = arr[0];
      } else {
        z = arr[i + 1];
      }
      if ((x === 1 && y === 1 && z === 1) || (x === 1 && y === 0 && z === 0) || (x === 0 && y === 0 && z === 0)) {
        console.log(x + ", " + y(", and " + z + " are 0"));
        arr[i] = 0;
      } else {
        console.log(x + ", " + y(", and " + z + " are 1"));
        arr[i] = 1;
      }
    }
    return arr;
  };

  myArr = [0, 0, 1, 1, 1, 0, 0];

  console.log(myArr);

  console.log(applyRule(myArr));

}).call(this);
